<HTML>
<BODY BGCOLOR="white">
<PRE>
<FONT color="green">001</FONT>    package com.googlecode.catchexception;<a name="line.1"></a>
<FONT color="green">002</FONT>    <a name="line.2"></a>
<FONT color="green">003</FONT>    import org.mockito.cglib.proxy.MethodInterceptor;<a name="line.3"></a>
<FONT color="green">004</FONT>    <a name="line.4"></a>
<FONT color="green">005</FONT>    import com.googlecode.catchexception.internal.DelegatingInterceptor;<a name="line.5"></a>
<FONT color="green">006</FONT>    import com.googlecode.catchexception.internal.ExceptionHolder;<a name="line.6"></a>
<FONT color="green">007</FONT>    import com.googlecode.catchexception.internal.ExceptionProcessingInterceptor;<a name="line.7"></a>
<FONT color="green">008</FONT>    import com.googlecode.catchexception.internal.InterfaceOnlyProxyFactory;<a name="line.8"></a>
<FONT color="green">009</FONT>    import com.googlecode.catchexception.internal.SubclassProxyFactory;<a name="line.9"></a>
<FONT color="green">010</FONT>    <a name="line.10"></a>
<FONT color="green">011</FONT>    /**<a name="line.11"></a>
<FONT color="green">012</FONT>     * The methods of this class catch and verify exceptions in &lt;em&gt;a single line of<a name="line.12"></a>
<FONT color="green">013</FONT>     * code&lt;/em&gt; and make them available for further analysis.<a name="line.13"></a>
<FONT color="green">014</FONT>     * <a name="line.14"></a>
<FONT color="green">015</FONT>     * &lt;h1&gt;Documentation&lt;/h1&gt;<a name="line.15"></a>
<FONT color="green">016</FONT>     * &lt;p&gt;<a name="line.16"></a>
<FONT color="green">017</FONT>     * &lt;b&gt; &lt;a href="#1"&gt;1. How to use catch-exception?&lt;/a&gt;&lt;br/&gt;<a name="line.17"></a>
<FONT color="green">018</FONT>     * &lt;a href="#2"&gt;2. What is this stuff actually good for?&lt;/a&gt; &lt;br/&gt;<a name="line.18"></a>
<FONT color="green">019</FONT>     * &lt;a href="#3"&gt;3. How does it work internally?&lt;/a&gt;&lt;br/&gt;<a name="line.19"></a>
<FONT color="green">020</FONT>     * &lt;a href="#4"&gt;4. When is the caught exception reset?&lt;/a&gt;&lt;br/&gt;<a name="line.20"></a>
<FONT color="green">021</FONT>     * &lt;a href="#5"&gt;5. My code throws a ClassCastException. Why?&lt;/a&gt; &lt;br/&gt;<a name="line.21"></a>
<FONT color="green">022</FONT>     * &lt;a href="#6"&gt;6. The exception is not caught. Why?&lt;/a&gt; &lt;br/&gt;<a name="line.22"></a>
<FONT color="green">023</FONT>     * &lt;a href="#7"&gt;7. Do I have to care about memory leaks?&lt;/a&gt; &lt;br/&gt;<a name="line.23"></a>
<FONT color="green">024</FONT>     * &lt;a href="#8"&gt;8. The caught exception is not available in another thread.<a name="line.24"></a>
<FONT color="green">025</FONT>     * Why?&lt;/a&gt;&lt;br/&gt;<a name="line.25"></a>
<FONT color="green">026</FONT>     * &lt;a href="#9"&gt;9. How do I catch an exception thrown by a static method?&lt;/a&gt; &lt;br/&gt;<a name="line.26"></a>
<FONT color="green">027</FONT>     * &lt;a href="#10"&gt;10. Is there a way to get rid of the throws clause in my test<a name="line.27"></a>
<FONT color="green">028</FONT>     * method?&lt;/a&gt; &lt;br/&gt;<a name="line.28"></a>
<FONT color="green">029</FONT>     * &lt;a href="#11"&gt;11. Can I catch errors instead of exceptions?&lt;/a&gt; &lt;br/&gt;<a name="line.29"></a>
<FONT color="green">030</FONT>     * <a name="line.30"></a>
<FONT color="green">031</FONT>     * <a name="line.31"></a>
<FONT color="green">032</FONT>     * <a name="line.32"></a>
<FONT color="green">033</FONT>     * &lt;/b&gt;<a name="line.33"></a>
<FONT color="green">034</FONT>     * &lt;p&gt;<a name="line.34"></a>
<FONT color="green">035</FONT>     * &lt;h3 id="1"&gt;1. How to use catch-exception?&lt;/h3&gt;<a name="line.35"></a>
<FONT color="green">036</FONT>     * &lt;p&gt;<a name="line.36"></a>
<FONT color="green">037</FONT>     * The most basic usage is:<a name="line.37"></a>
<FONT color="green">038</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;import static com.googlecode.catchexception.CatchException.*;<a name="line.38"></a>
<FONT color="green">039</FONT>    <a name="line.39"></a>
<FONT color="green">040</FONT>    // call customerService.prepareBilling(Prize.Zero)<a name="line.40"></a>
<FONT color="green">041</FONT>    // and catch the exception if any is thrown <a name="line.41"></a>
<FONT color="green">042</FONT>    catchException(customerService).prepareBilling(Prize.Zero);<a name="line.42"></a>
<FONT color="green">043</FONT>    <a name="line.43"></a>
<FONT color="green">044</FONT>    // assert that an IllegalArgumentException was thrown<a name="line.44"></a>
<FONT color="green">045</FONT>    assert caughtException() instanceof IllegalArgumentException;&lt;/pre&gt;&lt;/code&gt;<a name="line.45"></a>
<FONT color="green">046</FONT>     * &lt;p&gt;<a name="line.46"></a>
<FONT color="green">047</FONT>     * You can combine the two lines of code in a single one if you like:<a name="line.47"></a>
<FONT color="green">048</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;// call customerService.prepareBilling(Prize.Zero)<a name="line.48"></a>
<FONT color="green">049</FONT>    // and throw an ExceptionNotThrownAssertionError if<a name="line.49"></a>
<FONT color="green">050</FONT>    // the expected exception is not thrown <a name="line.50"></a>
<FONT color="green">051</FONT>    verifyException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);&lt;/pre&gt;&lt;/code&gt;<a name="line.51"></a>
<FONT color="green">052</FONT>     * There is a minor difference between both variants. In the first variant you<a name="line.52"></a>
<FONT color="green">053</FONT>     * must start the JVM with option &lt;code&gt;-ea&lt;/code&gt; to enable the assertion. The<a name="line.53"></a>
<FONT color="green">054</FONT>     * second variant does not use JDK assertions and ,therefore, always verifies<a name="line.54"></a>
<FONT color="green">055</FONT>     * the caught exception.<a name="line.55"></a>
<FONT color="green">056</FONT>     * &lt;p&gt;<a name="line.56"></a>
<FONT color="green">057</FONT>     * A third variant allows you to select the type of exceptions you want to catch<a name="line.57"></a>
<FONT color="green">058</FONT>     * (no verification involved):<a name="line.58"></a>
<FONT color="green">059</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;// catch IllegalArgumentExceptions but no other exceptions <a name="line.59"></a>
<FONT color="green">060</FONT>    catchException(customerService, IllegalArgumentException.class).prepareBilling(Prize.Zero);&lt;/pre&gt;&lt;/code&gt;<a name="line.60"></a>
<FONT color="green">061</FONT>     * &lt;p&gt;<a name="line.61"></a>
<FONT color="green">062</FONT>     * The fourth and last variant verifies that some exception is thrown, i.e. the<a name="line.62"></a>
<FONT color="green">063</FONT>     * type of the exception does not matter:<a name="line.63"></a>
<FONT color="green">064</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;verifyException(customerService).prepareBilling(Prize.Zero);&lt;/pre&gt;&lt;/code&gt;<a name="line.64"></a>
<FONT color="green">065</FONT>     * &lt;p&gt;<a name="line.65"></a>
<FONT color="green">066</FONT>     * In all variants you can use &lt;code&gt;caughtException()&lt;/code&gt; afterwards to<a name="line.66"></a>
<FONT color="green">067</FONT>     * inspect the caught exception.<a name="line.67"></a>
<FONT color="green">068</FONT>     * &lt;h3 id="2"&gt;2. What is this stuff actually good for?&lt;/h3&gt;<a name="line.68"></a>
<FONT color="green">069</FONT>     * &lt;p&gt;<a name="line.69"></a>
<FONT color="green">070</FONT>     * This class targets concise and robust code in tests. Dadid Saff, a commiter<a name="line.70"></a>
<FONT color="green">071</FONT>     * to JUnit, has &lt;a<a name="line.71"></a>
<FONT color="green">072</FONT>     * href="http://shareandenjoy.saff.net/2006/12/assertthrownexception_20.html"<a name="line.72"></a>
<FONT color="green">073</FONT>     * &gt;discussed&lt;/a&gt; this approach in 2007. Let me summarize the arguments here.<a name="line.73"></a>
<FONT color="green">074</FONT>     * &lt;p&gt;<a name="line.74"></a>
<FONT color="green">075</FONT>     * There are two advantages of the approach proposed here in comparison to the<a name="line.75"></a>
<FONT color="green">076</FONT>     * use of try/catch blocks.<a name="line.76"></a>
<FONT color="green">077</FONT>     * &lt;ul&gt;<a name="line.77"></a>
<FONT color="green">078</FONT>     * &lt;li&gt;The test is more concise and easier to read.<a name="line.78"></a>
<FONT color="green">079</FONT>     * &lt;li&gt;The test cannot be corrupted by a missing assertion. Assume you forgot to<a name="line.79"></a>
<FONT color="green">080</FONT>     * type &lt;code&gt;fail()&lt;/code&gt; behind the method call that is expected to throw an<a name="line.80"></a>
<FONT color="green">081</FONT>     * exception.<a name="line.81"></a>
<FONT color="green">082</FONT>     * &lt;/ul&gt;<a name="line.82"></a>
<FONT color="green">083</FONT>     * &lt;p&gt;<a name="line.83"></a>
<FONT color="green">084</FONT>     * There are also some advantages of this approach in comparison to test<a name="line.84"></a>
<FONT color="green">085</FONT>     * runner-specific mechanisms that catch and verify exceptions.<a name="line.85"></a>
<FONT color="green">086</FONT>     * &lt;ul&gt;<a name="line.86"></a>
<FONT color="green">087</FONT>     * &lt;li&gt;A single test can verify more than one thrown exception.<a name="line.87"></a>
<FONT color="green">088</FONT>     * &lt;li&gt;The test can verify the properties of the thrown exception after the<a name="line.88"></a>
<FONT color="green">089</FONT>     * exception is caught.<a name="line.89"></a>
<FONT color="green">090</FONT>     * &lt;li&gt;The test can specify by which method call the exception must be thrown.<a name="line.90"></a>
<FONT color="green">091</FONT>     * &lt;li&gt;The test does not depend on a specific test runner (JUnit4, TestNG).<a name="line.91"></a>
<FONT color="green">092</FONT>     * &lt;/ul&gt;<a name="line.92"></a>
<FONT color="green">093</FONT>     * &lt;p&gt;<a name="line.93"></a>
<FONT color="green">094</FONT>     * &lt;h3 id="3"&gt;3. How does it work internally?&lt;/h3&gt;<a name="line.94"></a>
<FONT color="green">095</FONT>     * &lt;p&gt;<a name="line.95"></a>
<FONT color="green">096</FONT>     * The method &lt;code&gt;catchException(obj)&lt;/code&gt; wraps the given object with a<a name="line.96"></a>
<FONT color="green">097</FONT>     * proxy that catches the exception, then (optionally) verifies the exception,<a name="line.97"></a>
<FONT color="green">098</FONT>     * and finally attaches the exception to the current &lt;a<a name="line.98"></a>
<FONT color="green">099</FONT>     * name="threadlocal"&gt;thread&lt;/a&gt; for further analysis. The &lt;a<a name="line.99"></a>
<FONT color="green">100</FONT>     * href="#proxies"&gt;known limitations&lt;/a&gt; for proxies apply.<a name="line.100"></a>
<FONT color="green">101</FONT>     * &lt;p&gt;<a name="line.101"></a>
<FONT color="green">102</FONT>     * Is both memory consumption and runtime a concern for you? Then use try/catch<a name="line.102"></a>
<FONT color="green">103</FONT>     * blocks instead of this class. Because in this case the creation of proxies is<a name="line.103"></a>
<FONT color="green">104</FONT>     * an unnecessary overhead. If only either memory consumption or runtime is an<a name="line.104"></a>
<FONT color="green">105</FONT>     * issue for you, feel free to configure the cache of the underlying proxy<a name="line.105"></a>
<FONT color="green">106</FONT>     * factories as appropriate.<a name="line.106"></a>
<FONT color="green">107</FONT>     * &lt;h3 id="4"&gt;4. When is the caught exception reset?&lt;/h3&gt;<a name="line.107"></a>
<FONT color="green">108</FONT>     * &lt;p&gt;<a name="line.108"></a>
<FONT color="green">109</FONT>     * The Method {@link #caughtException()} returns the exception thrown by the<a name="line.109"></a>
<FONT color="green">110</FONT>     * last method call on a proxied object in the current thread, i.e. it is reset<a name="line.110"></a>
<FONT color="green">111</FONT>     * by calling a method on the proxied object. If the called method has not<a name="line.111"></a>
<FONT color="green">112</FONT>     * thrown an exception, &lt;code&gt;caughtException()&lt;/code&gt; returns null.<a name="line.112"></a>
<FONT color="green">113</FONT>     * &lt;p&gt;<a name="line.113"></a>
<FONT color="green">114</FONT>     * To reset the caught exception manually, call {@link #resetCaughtException()}.<a name="line.114"></a>
<FONT color="green">115</FONT>     * At the moment there is no way to reset exceptions that have been caught in<a name="line.115"></a>
<FONT color="green">116</FONT>     * other threads.<a name="line.116"></a>
<FONT color="green">117</FONT>     * &lt;h3 id="5"&gt;&lt;a name="proxies" /&gt;5. My code throws a ClassCastException. Why?&lt;/h3&gt;<a name="line.117"></a>
<FONT color="green">118</FONT>     * &lt;p&gt;<a name="line.118"></a>
<FONT color="green">119</FONT>     * Example:<a name="line.119"></a>
<FONT color="green">120</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;StringBuilder sb = new StringBuilder();<a name="line.120"></a>
<FONT color="green">121</FONT>    catchException(sb).charAt(-2); // throws ClassCastException&lt;/pre&gt;&lt;/code&gt;<a name="line.121"></a>
<FONT color="green">122</FONT>     * &lt;p&gt;<a name="line.122"></a>
<FONT color="green">123</FONT>     * Probably you have tested a final class. Proxy factories usually try to<a name="line.123"></a>
<FONT color="green">124</FONT>     * subclass the type of the proxied object. This is not possible if the original<a name="line.124"></a>
<FONT color="green">125</FONT>     * class is final. But there is a way out. If the tested method belongs to an<a name="line.125"></a>
<FONT color="green">126</FONT>     * interface, then you can cast the argument (here: &lt;code&gt;sb&lt;/code&gt;) to that<a name="line.126"></a>
<FONT color="green">127</FONT>     * interface or ,easier, change the declared type of the argument to the<a name="line.127"></a>
<FONT color="green">128</FONT>     * interface type. This works because the created proxy is not longer required<a name="line.128"></a>
<FONT color="green">129</FONT>     * to have the same type as the original class but it must only have the same<a name="line.129"></a>
<FONT color="green">130</FONT>     * interface.<a name="line.130"></a>
<FONT color="green">131</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;// first variant<a name="line.131"></a>
<FONT color="green">132</FONT>    StringBuilder sb = new StringBuilder();<a name="line.132"></a>
<FONT color="green">133</FONT>    catchException((CharSequence) sb).charAt(-2); // works fine<a name="line.133"></a>
<FONT color="green">134</FONT>    <a name="line.134"></a>
<FONT color="green">135</FONT>    // second variant<a name="line.135"></a>
<FONT color="green">136</FONT>    CharSequence sb = new StringBuilder();<a name="line.136"></a>
<FONT color="green">137</FONT>    catchException(sb).charAt(-2); // works fine&lt;/pre&gt;&lt;/code&gt; If the tested<a name="line.137"></a>
<FONT color="green">138</FONT>     * method does no belong to an interface fall back to the try/catch-blocks.<a name="line.138"></a>
<FONT color="green">139</FONT>     * &lt;h3 id="6"&gt;6. The exception is not caught. Why?&lt;/h3&gt;<a name="line.139"></a>
<FONT color="green">140</FONT>     * &lt;p&gt;<a name="line.140"></a>
<FONT color="green">141</FONT>     * Example:<a name="line.141"></a>
<FONT color="green">142</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;ServiceImpl impl = new ServiceImpl();<a name="line.142"></a>
<FONT color="green">143</FONT>    catchException(impl).do(); // do() is a final method that throws an exception&lt;/pre&gt;&lt;/code&gt;<a name="line.143"></a>
<FONT color="green">144</FONT>     * &lt;p&gt;<a name="line.144"></a>
<FONT color="green">145</FONT>     * Probably you have tested a final method. If that tested method belongs to an<a name="line.145"></a>
<FONT color="green">146</FONT>     * interface you could use {@link #interfaces(Object)} to fix that problem. But<a name="line.146"></a>
<FONT color="green">147</FONT>     * then the syntax starts to become ugly.<a name="line.147"></a>
<FONT color="green">148</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;Service api = new ServiceImpl();<a name="line.148"></a>
<FONT color="green">149</FONT>    catchException(interfaces(api)).do(); // works fine&lt;/pre&gt;&lt;/code&gt; I recommend<a name="line.149"></a>
<FONT color="green">150</FONT>     * to use try/catch blocks in such cases.<a name="line.150"></a>
<FONT color="green">151</FONT>     * <a name="line.151"></a>
<FONT color="green">152</FONT>     * &lt;h3 id="7"&gt;7. Do I have to care about memory leaks?&lt;/h3&gt;<a name="line.152"></a>
<FONT color="green">153</FONT>     * &lt;p&gt;<a name="line.153"></a>
<FONT color="green">154</FONT>     * This library uses a {@link ThreadLocal}. ThreadLocals are known to cause<a name="line.154"></a>
<FONT color="green">155</FONT>     * memory leaks if they refer to a class the garbage collector would like to<a name="line.155"></a>
<FONT color="green">156</FONT>     * collect. If you use this library only for testing, then memory leaks do not<a name="line.156"></a>
<FONT color="green">157</FONT>     * worry you. If you use this library for other purposes than testing, you<a name="line.157"></a>
<FONT color="green">158</FONT>     * should care.<a name="line.158"></a>
<FONT color="green">159</FONT>     * &lt;p&gt;<a name="line.159"></a>
<FONT color="green">160</FONT>     * &lt;h3 id="8"&gt;8. The caught exception is not available in another thread. Why?&lt;/h3&gt;<a name="line.160"></a>
<FONT color="green">161</FONT>     * &lt;p&gt;<a name="line.161"></a>
<FONT color="green">162</FONT>     * The caught exception is saved &lt;a href="#threadlocal"&gt;at the thread&lt;/a&gt; the<a name="line.162"></a>
<FONT color="green">163</FONT>     * exception is thrown in. This is the reason the exception is not visible<a name="line.163"></a>
<FONT color="green">164</FONT>     * within any other thread.<a name="line.164"></a>
<FONT color="green">165</FONT>     * &lt;h3 id="9"&gt;9. How do I catch an exception thrown by a static method?&lt;/h3&gt;<a name="line.165"></a>
<FONT color="green">166</FONT>     * &lt;p&gt;<a name="line.166"></a>
<FONT color="green">167</FONT>     * Unfortunately, catch-exception does not support this. Fall back on try/catch<a name="line.167"></a>
<FONT color="green">168</FONT>     * blocks.<a name="line.168"></a>
<FONT color="green">169</FONT>     * &lt;h3 id="10"&gt;10. Is there a way to get rid of the throws clause in my test<a name="line.169"></a>
<FONT color="green">170</FONT>     * method?&lt;/h3&gt;<a name="line.170"></a>
<FONT color="green">171</FONT>     * &lt;p&gt;<a name="line.171"></a>
<FONT color="green">172</FONT>     * Example:<a name="line.172"></a>
<FONT color="green">173</FONT>     * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;public void testSomething() throws Exception {<a name="line.173"></a>
<FONT color="green">174</FONT>        ...<a name="line.174"></a>
<FONT color="green">175</FONT>        catchException(obj).do(); // do() throws a checked exception&lt;/pre&gt;&lt;/code&gt; No,<a name="line.175"></a>
<FONT color="green">176</FONT>     * although the exception is always caught you cannot omit the throws clause in<a name="line.176"></a>
<FONT color="green">177</FONT>     * your test method.<a name="line.177"></a>
<FONT color="green">178</FONT>     * &lt;h3 id="11"&gt;11. Can I catch errors instead of exceptions?&lt;/h3&gt;<a name="line.178"></a>
<FONT color="green">179</FONT>     * &lt;p&gt;<a name="line.179"></a>
<FONT color="green">180</FONT>     * At the moment you cannot catch {@link Throwable throwables} that are not<a name="line.180"></a>
<FONT color="green">181</FONT>     * {@link Exception exceptions}. But this could be easily changed if someone<a name="line.181"></a>
<FONT color="green">182</FONT>     * wants to get this feature.<a name="line.182"></a>
<FONT color="green">183</FONT>     * <a name="line.183"></a>
<FONT color="green">184</FONT>     * @author rwoo<a name="line.184"></a>
<FONT color="green">185</FONT>     * @since 16.09.2011<a name="line.185"></a>
<FONT color="green">186</FONT>     */<a name="line.186"></a>
<FONT color="green">187</FONT>    public class CatchException {<a name="line.187"></a>
<FONT color="green">188</FONT>    <a name="line.188"></a>
<FONT color="green">189</FONT>        /**<a name="line.189"></a>
<FONT color="green">190</FONT>         * Returns the exception caught during the last call on the proxied object<a name="line.190"></a>
<FONT color="green">191</FONT>         * in the current thread.<a name="line.191"></a>
<FONT color="green">192</FONT>         * <a name="line.192"></a>
<FONT color="green">193</FONT>         * @param &lt;E&gt;<a name="line.193"></a>
<FONT color="green">194</FONT>         *            This type parameter makes some type casts redundant.<a name="line.194"></a>
<FONT color="green">195</FONT>         * @return Returns the exception caught during the last call on the proxied<a name="line.195"></a>
<FONT color="green">196</FONT>         *         object in the current thread - if the call was made through a<a name="line.196"></a>
<FONT color="green">197</FONT>         *         proxy that has been created via<a name="line.197"></a>
<FONT color="green">198</FONT>         *         {@link #verifyException(Object, Class) verifyException()} or<a name="line.198"></a>
<FONT color="green">199</FONT>         *         {@link #catchException(Object, Class) catchException()}. Returns<a name="line.199"></a>
<FONT color="green">200</FONT>         *         null the proxy has not caught an exception. Returns null if the<a name="line.200"></a>
<FONT color="green">201</FONT>         *         caught exception belongs to a class that is no longer<a name="line.201"></a>
<FONT color="green">202</FONT>         *         {@link ClassLoader loaded}.<a name="line.202"></a>
<FONT color="green">203</FONT>         */<a name="line.203"></a>
<FONT color="green">204</FONT>        public static &lt;E extends Exception&gt; E caughtException() {<a name="line.204"></a>
<FONT color="green">205</FONT>            return ExceptionHolder.&lt;E&gt; get();<a name="line.205"></a>
<FONT color="green">206</FONT>        }<a name="line.206"></a>
<FONT color="green">207</FONT>    <a name="line.207"></a>
<FONT color="green">208</FONT>        /**<a name="line.208"></a>
<FONT color="green">209</FONT>         * Use it to verify that an exception is thrown and to get access to the<a name="line.209"></a>
<FONT color="green">210</FONT>         * thrown exception (for further verifications).<a name="line.210"></a>
<FONT color="green">211</FONT>         * &lt;p&gt;<a name="line.211"></a>
<FONT color="green">212</FONT>         * The following example verifies that obj.doX() throws a Exception:<a name="line.212"></a>
<FONT color="green">213</FONT>         * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;verifyException(obj).doX(); // catch and verify<a name="line.213"></a>
<FONT color="green">214</FONT>    assert "foobar".equals(caughtException().getMessage()); // further analysis<a name="line.214"></a>
<FONT color="green">215</FONT>    &lt;/pre&gt;&lt;/code&gt;<a name="line.215"></a>
<FONT color="green">216</FONT>         * &lt;p&gt;<a name="line.216"></a>
<FONT color="green">217</FONT>         * If &lt;code&gt;doX()&lt;/code&gt; does not throw a &lt;code&gt;Exception&lt;/code&gt;, then a<a name="line.217"></a>
<FONT color="green">218</FONT>         * {@link ExceptionNotThrownAssertionError} is thrown. Otherwise the thrown<a name="line.218"></a>
<FONT color="green">219</FONT>         * exception can be retrieved via {@link #caughtException()}.<a name="line.219"></a>
<FONT color="green">220</FONT>         * &lt;p&gt;<a name="line.220"></a>
<FONT color="green">221</FONT>         * <a name="line.221"></a>
<FONT color="green">222</FONT>         * @param &lt;T&gt;<a name="line.222"></a>
<FONT color="green">223</FONT>         *            The type of the given &lt;code&gt;obj&lt;/code&gt;.<a name="line.223"></a>
<FONT color="green">224</FONT>         * <a name="line.224"></a>
<FONT color="green">225</FONT>         * @param obj<a name="line.225"></a>
<FONT color="green">226</FONT>         *            The instance that shall be proxied. Must not be<a name="line.226"></a>
<FONT color="green">227</FONT>         *            &lt;code&gt;null&lt;/code&gt;.<a name="line.227"></a>
<FONT color="green">228</FONT>         * @return Returns an object that verifies that each invocation on the<a name="line.228"></a>
<FONT color="green">229</FONT>         *         underlying object throws an exception.<a name="line.229"></a>
<FONT color="green">230</FONT>         */<a name="line.230"></a>
<FONT color="green">231</FONT>        public static &lt;T&gt; T verifyException(T obj) {<a name="line.231"></a>
<FONT color="green">232</FONT>            return verifyException(obj, Exception.class);<a name="line.232"></a>
<FONT color="green">233</FONT>        }<a name="line.233"></a>
<FONT color="green">234</FONT>    <a name="line.234"></a>
<FONT color="green">235</FONT>        /**<a name="line.235"></a>
<FONT color="green">236</FONT>         * Use it to verify that an exception of specific type is thrown and to get<a name="line.236"></a>
<FONT color="green">237</FONT>         * access to the thrown exception (for further verifications).<a name="line.237"></a>
<FONT color="green">238</FONT>         * &lt;p&gt;<a name="line.238"></a>
<FONT color="green">239</FONT>         * The following example verifies that obj.doX() throws a MyException:<a name="line.239"></a>
<FONT color="green">240</FONT>         * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;verifyException(obj, MyException.class).doX(); // catch and verify<a name="line.240"></a>
<FONT color="green">241</FONT>    assert "foobar".equals(caughtException().getMessage()); // further analysis<a name="line.241"></a>
<FONT color="green">242</FONT>    &lt;/pre&gt;&lt;/code&gt;<a name="line.242"></a>
<FONT color="green">243</FONT>         * &lt;p&gt;<a name="line.243"></a>
<FONT color="green">244</FONT>         * If &lt;code&gt;doX()&lt;/code&gt; does not throw a &lt;code&gt;MyException&lt;/code&gt;, then a<a name="line.244"></a>
<FONT color="green">245</FONT>         * {@link ExceptionNotThrownAssertionError} is thrown. Otherwise the thrown<a name="line.245"></a>
<FONT color="green">246</FONT>         * exception can be retrieved via {@link #caughtException()}.<a name="line.246"></a>
<FONT color="green">247</FONT>         * &lt;p&gt;<a name="line.247"></a>
<FONT color="green">248</FONT>         * <a name="line.248"></a>
<FONT color="green">249</FONT>         * @param &lt;T&gt;<a name="line.249"></a>
<FONT color="green">250</FONT>         *            The type of the given &lt;code&gt;obj&lt;/code&gt;.<a name="line.250"></a>
<FONT color="green">251</FONT>         * <a name="line.251"></a>
<FONT color="green">252</FONT>         * @param &lt;E&gt;<a name="line.252"></a>
<FONT color="green">253</FONT>         *            The type of the exception that shall be caught.<a name="line.253"></a>
<FONT color="green">254</FONT>         * @param obj<a name="line.254"></a>
<FONT color="green">255</FONT>         *            The instance that shall be proxied. Must not be<a name="line.255"></a>
<FONT color="green">256</FONT>         *            &lt;code&gt;null&lt;/code&gt;.<a name="line.256"></a>
<FONT color="green">257</FONT>         * @param clazz<a name="line.257"></a>
<FONT color="green">258</FONT>         *            The type of the exception that shall be thrown by the<a name="line.258"></a>
<FONT color="green">259</FONT>         *            underlying object. Must not be &lt;code&gt;null&lt;/code&gt;.<a name="line.259"></a>
<FONT color="green">260</FONT>         * @return Returns an object that verifies that each invocation on the<a name="line.260"></a>
<FONT color="green">261</FONT>         *         underlying object throws an exception of the given type.<a name="line.261"></a>
<FONT color="green">262</FONT>         */<a name="line.262"></a>
<FONT color="green">263</FONT>        public static &lt;T, E extends Exception&gt; T verifyException(T obj,<a name="line.263"></a>
<FONT color="green">264</FONT>                Class&lt;E&gt; clazz) {<a name="line.264"></a>
<FONT color="green">265</FONT>    <a name="line.265"></a>
<FONT color="green">266</FONT>            return processException(obj, clazz, true);<a name="line.266"></a>
<FONT color="green">267</FONT>        }<a name="line.267"></a>
<FONT color="green">268</FONT>    <a name="line.268"></a>
<FONT color="green">269</FONT>        /**<a name="line.269"></a>
<FONT color="green">270</FONT>         * Use it to catch an exception and to get access to the thrown exception<a name="line.270"></a>
<FONT color="green">271</FONT>         * (for further verifications).<a name="line.271"></a>
<FONT color="green">272</FONT>         * &lt;p&gt;<a name="line.272"></a>
<FONT color="green">273</FONT>         * In the following example you catch exceptions that are thrown by<a name="line.273"></a>
<FONT color="green">274</FONT>         * obj.doX():<a name="line.274"></a>
<FONT color="green">275</FONT>         * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;catchException(obj).doX(); // catch<a name="line.275"></a>
<FONT color="green">276</FONT>    if (caughtException() != null) {<a name="line.276"></a>
<FONT color="green">277</FONT>        assert "foobar".equals(caughtException().getMessage()); // further analysis<a name="line.277"></a>
<FONT color="green">278</FONT>    }&lt;/pre&gt;&lt;/code&gt;<a name="line.278"></a>
<FONT color="green">279</FONT>         * If &lt;code&gt;doX()&lt;/code&gt; throws a exception, then {@link #caughtException()}<a name="line.279"></a>
<FONT color="green">280</FONT>         * will return the caught exception. If &lt;code&gt;doX()&lt;/code&gt; does not throw a<a name="line.280"></a>
<FONT color="green">281</FONT>         * exception, then {@link #caughtException()} will return &lt;code&gt;null&lt;/code&gt;.<a name="line.281"></a>
<FONT color="green">282</FONT>         * &lt;p&gt;<a name="line.282"></a>
<FONT color="green">283</FONT>         * <a name="line.283"></a>
<FONT color="green">284</FONT>         * @param &lt;T&gt;<a name="line.284"></a>
<FONT color="green">285</FONT>         *            The type of the given &lt;code&gt;obj&lt;/code&gt;.<a name="line.285"></a>
<FONT color="green">286</FONT>         * <a name="line.286"></a>
<FONT color="green">287</FONT>         * @param obj<a name="line.287"></a>
<FONT color="green">288</FONT>         *            The instance that shall be proxied. Must not be<a name="line.288"></a>
<FONT color="green">289</FONT>         *            &lt;code&gt;null&lt;/code&gt;.<a name="line.289"></a>
<FONT color="green">290</FONT>         * @return Returns a proxy for the given object. The proxy catches<a name="line.290"></a>
<FONT color="green">291</FONT>         *         exceptions of the given type when a method on the proxy is<a name="line.291"></a>
<FONT color="green">292</FONT>         *         called.<a name="line.292"></a>
<FONT color="green">293</FONT>         */<a name="line.293"></a>
<FONT color="green">294</FONT>        public static &lt;T&gt; T catchException(T obj) {<a name="line.294"></a>
<FONT color="green">295</FONT>    <a name="line.295"></a>
<FONT color="green">296</FONT>            return processException(obj, Exception.class, false);<a name="line.296"></a>
<FONT color="green">297</FONT>        }<a name="line.297"></a>
<FONT color="green">298</FONT>    <a name="line.298"></a>
<FONT color="green">299</FONT>        /**<a name="line.299"></a>
<FONT color="green">300</FONT>         * Use it to catch an exception of a specific type and to get access to the<a name="line.300"></a>
<FONT color="green">301</FONT>         * thrown exception (for further verifications).<a name="line.301"></a>
<FONT color="green">302</FONT>         * &lt;p&gt;<a name="line.302"></a>
<FONT color="green">303</FONT>         * In the following example you catch exceptions of type MyException that<a name="line.303"></a>
<FONT color="green">304</FONT>         * are thrown by obj.doX():<a name="line.304"></a>
<FONT color="green">305</FONT>         * &lt;code&gt;&lt;pre class="prettyprint lang-java"&gt;catchException(obj, MyException.class).doX(); // catch<a name="line.305"></a>
<FONT color="green">306</FONT>    if (caughtException() != null) {<a name="line.306"></a>
<FONT color="green">307</FONT>        assert "foobar".equals(caughtException().getMessage()); // further analysis<a name="line.307"></a>
<FONT color="green">308</FONT>    }&lt;/pre&gt;&lt;/code&gt;<a name="line.308"></a>
<FONT color="green">309</FONT>         * If &lt;code&gt;doX()&lt;/code&gt; throws a &lt;code&gt;MyException&lt;/code&gt;, then<a name="line.309"></a>
<FONT color="green">310</FONT>         * {@link #caughtException()} will return the caught exception. If<a name="line.310"></a>
<FONT color="green">311</FONT>         * &lt;code&gt;doX()&lt;/code&gt; does not throw a &lt;code&gt;MyException&lt;/code&gt;, then<a name="line.311"></a>
<FONT color="green">312</FONT>         * {@link #caughtException()} will return &lt;code&gt;null&lt;/code&gt;. If<a name="line.312"></a>
<FONT color="green">313</FONT>         * &lt;code&gt;doX()&lt;/code&gt; throws an exception of another type, i.e. not a<a name="line.313"></a>
<FONT color="green">314</FONT>         * subclass but another class, then this exception is not thrown and<a name="line.314"></a>
<FONT color="green">315</FONT>         * {@link #caughtException()} will return &lt;code&gt;null&lt;/code&gt;.<a name="line.315"></a>
<FONT color="green">316</FONT>         * &lt;p&gt;<a name="line.316"></a>
<FONT color="green">317</FONT>         * <a name="line.317"></a>
<FONT color="green">318</FONT>         * @param &lt;T&gt;<a name="line.318"></a>
<FONT color="green">319</FONT>         *            The type of the given &lt;code&gt;obj&lt;/code&gt;.<a name="line.319"></a>
<FONT color="green">320</FONT>         * <a name="line.320"></a>
<FONT color="green">321</FONT>         * @param &lt;E&gt;<a name="line.321"></a>
<FONT color="green">322</FONT>         *            The type of the exception that shall be caught.<a name="line.322"></a>
<FONT color="green">323</FONT>         * @param obj<a name="line.323"></a>
<FONT color="green">324</FONT>         *            The instance that shall be proxied. Must not be<a name="line.324"></a>
<FONT color="green">325</FONT>         *            &lt;code&gt;null&lt;/code&gt;.<a name="line.325"></a>
<FONT color="green">326</FONT>         * @param clazz<a name="line.326"></a>
<FONT color="green">327</FONT>         *            The type of the exception that shall be caught. Must not be<a name="line.327"></a>
<FONT color="green">328</FONT>         *            &lt;code&gt;null&lt;/code&gt;.<a name="line.328"></a>
<FONT color="green">329</FONT>         * @return Returns a proxy for the given object. The proxy catches<a name="line.329"></a>
<FONT color="green">330</FONT>         *         exceptions of the given type when a method on the proxy is<a name="line.330"></a>
<FONT color="green">331</FONT>         *         called.<a name="line.331"></a>
<FONT color="green">332</FONT>         */<a name="line.332"></a>
<FONT color="green">333</FONT>        public static &lt;T, E extends Exception&gt; T catchException(T obj,<a name="line.333"></a>
<FONT color="green">334</FONT>                Class&lt;E&gt; clazz) {<a name="line.334"></a>
<FONT color="green">335</FONT>    <a name="line.335"></a>
<FONT color="green">336</FONT>            return processException(obj, clazz, false);<a name="line.336"></a>
<FONT color="green">337</FONT>        }<a name="line.337"></a>
<FONT color="green">338</FONT>    <a name="line.338"></a>
<FONT color="green">339</FONT>        /**<a name="line.339"></a>
<FONT color="green">340</FONT>         * Creates a proxy that processes exceptions thrown by the underlying<a name="line.340"></a>
<FONT color="green">341</FONT>         * object.<a name="line.341"></a>
<FONT color="green">342</FONT>         * &lt;p&gt;<a name="line.342"></a>
<FONT color="green">343</FONT>         * Delegates to<a name="line.343"></a>
<FONT color="green">344</FONT>         * {@link SubclassProxyFactory#createProxy(Class, MethodInterceptor)} which<a name="line.344"></a>
<FONT color="green">345</FONT>         * itself might delegate to<a name="line.345"></a>
<FONT color="green">346</FONT>         * {@link InterfaceOnlyProxyFactory#createProxy(Class, MethodInterceptor)}.<a name="line.346"></a>
<FONT color="green">347</FONT>         */<a name="line.347"></a>
<FONT color="green">348</FONT>        @SuppressWarnings("javadoc")<a name="line.348"></a>
<FONT color="green">349</FONT>        private static &lt;T, E extends Exception&gt; T processException(T obj,<a name="line.349"></a>
<FONT color="green">350</FONT>                Class&lt;E&gt; exceptionClazz, boolean assertException) {<a name="line.350"></a>
<FONT color="green">351</FONT>    <a name="line.351"></a>
<FONT color="green">352</FONT>            if (obj == null) {<a name="line.352"></a>
<FONT color="green">353</FONT>                throw new IllegalArgumentException("obj must not be null");<a name="line.353"></a>
<FONT color="green">354</FONT>            }<a name="line.354"></a>
<FONT color="green">355</FONT>    <a name="line.355"></a>
<FONT color="green">356</FONT>            return new SubclassProxyFactory().&lt;T&gt; createProxy(obj.getClass(),<a name="line.356"></a>
<FONT color="green">357</FONT>                    new ExceptionProcessingInterceptor&lt;E&gt;(obj, exceptionClazz,<a name="line.357"></a>
<FONT color="green">358</FONT>                            assertException));<a name="line.358"></a>
<FONT color="green">359</FONT>    <a name="line.359"></a>
<FONT color="green">360</FONT>        }<a name="line.360"></a>
<FONT color="green">361</FONT>    <a name="line.361"></a>
<FONT color="green">362</FONT>        /**<a name="line.362"></a>
<FONT color="green">363</FONT>         * Returns a proxy that implements all interfaces of the underlying object.<a name="line.363"></a>
<FONT color="green">364</FONT>         * <a name="line.364"></a>
<FONT color="green">365</FONT>         * @param &lt;T&gt;<a name="line.365"></a>
<FONT color="green">366</FONT>         *            must be an interface the object implements<a name="line.366"></a>
<FONT color="green">367</FONT>         * @param obj<a name="line.367"></a>
<FONT color="green">368</FONT>         *            the object that created proxy will delegate all calls to<a name="line.368"></a>
<FONT color="green">369</FONT>         * @return Returns a proxy that implements all interfaces of the underlying<a name="line.369"></a>
<FONT color="green">370</FONT>         *         object and delegates all calls to that underlying object.<a name="line.370"></a>
<FONT color="green">371</FONT>         */<a name="line.371"></a>
<FONT color="green">372</FONT>        public static &lt;T&gt; T interfaces(T obj) {<a name="line.372"></a>
<FONT color="green">373</FONT>    <a name="line.373"></a>
<FONT color="green">374</FONT>            if (obj == null) {<a name="line.374"></a>
<FONT color="green">375</FONT>                throw new IllegalArgumentException("obj must not be null");<a name="line.375"></a>
<FONT color="green">376</FONT>            }<a name="line.376"></a>
<FONT color="green">377</FONT>    <a name="line.377"></a>
<FONT color="green">378</FONT>            return new InterfaceOnlyProxyFactory().&lt;T&gt; createProxy(obj.getClass(),<a name="line.378"></a>
<FONT color="green">379</FONT>                    new DelegatingInterceptor(obj));<a name="line.379"></a>
<FONT color="green">380</FONT>        }<a name="line.380"></a>
<FONT color="green">381</FONT>    <a name="line.381"></a>
<FONT color="green">382</FONT>        /**<a name="line.382"></a>
<FONT color="green">383</FONT>         * Sets the {@link #caughtException() caught exception} to null. This does<a name="line.383"></a>
<FONT color="green">384</FONT>         * not affect exceptions saved at threads other than the current one.<a name="line.384"></a>
<FONT color="green">385</FONT>         * &lt;p&gt;<a name="line.385"></a>
<FONT color="green">386</FONT>         * Actually you probably never need to call this method because each method<a name="line.386"></a>
<FONT color="green">387</FONT>         * call on a proxied object in the current thread resets the caught<a name="line.387"></a>
<FONT color="green">388</FONT>         * exception. But if you want to improve test isolation or if you want to<a name="line.388"></a>
<FONT color="green">389</FONT>         * 'clean up' after testing (to avoid memory leaks), call the method before<a name="line.389"></a>
<FONT color="green">390</FONT>         * or after testing.<a name="line.390"></a>
<FONT color="green">391</FONT>         */<a name="line.391"></a>
<FONT color="green">392</FONT>        public static void resetCaughtException() {<a name="line.392"></a>
<FONT color="green">393</FONT>            ExceptionHolder.set(null);<a name="line.393"></a>
<FONT color="green">394</FONT>        }<a name="line.394"></a>
<FONT color="green">395</FONT>    <a name="line.395"></a>
<FONT color="green">396</FONT>    }<a name="line.396"></a>




























































</PRE>
</BODY>
</HTML>
